[Interface]
PrivateKey = APazxGAkUCv/Zu+9iA1NR42Dd+9Ishkq0n2Eiv3/sE0=
Address = 10.66.66.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = +no0CIBeE3x8TCC0xJp0vE70wrsBSGJIrr5nBSbpmBw=
Endpoint = 89.127.203.246:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25