[Interface]
PrivateKey = yG2FFN/xe5V/awtFSds3MwapfUJqMcMgDDFOnx3GVkg=
Address = 10.66.66.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = WQRNtvsEDsbYOYXbbVnt9t8daqmVOGhM2fZI4fUHsk0=
Endpoint = 89.127.203.246:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25