[Interface]
PrivateKey = 
Address = 10.66.66.2/24
DNS = 8.8.8.8

[Peer]
Endpoint = 89.127.203.246:53
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
PublicKey = RVWJRrsq1gFBhOzjPGP/jXFKjbg882rBPn2LmeXyJQk=
